services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-python-bot
    working_dir: /app
    command: python main.py
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./app:/app
    restart: unless-stopped
